name: run workflow

on:
  push:
    branches-ignore:
      - master
      - main
      - development

jobs:
  run-all-tests:
    runs-on: self-hosted
    steps :
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
          maven-version: 3.9.3

      - name: All the tests and Coverage Checks
        run: mvn clean install