name: run workflow

on:
  push:
    branches-ignore:
      - master
      - main
      - development

jobs:
  run-all-tests:
    runs-on: self-hosted
    steps :
      - name: 'Cleanup build folder'
        run: |
          echo "Current directory:"
          pwd
          echo "Before cleanup:"
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "After cleanup:"
          ls -la ./
      

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-jdk17-maven3.9.3
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Setup maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
          maven-version: 3.9.3
          java-version: 17

      - name: All the tests and Coverage Checks
        run: mvn clean install

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
         name: coverage-report
         path: target/site/jacoco/index.html